// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using propertiesService.Entities;

namespace propertiesService.Migrations
{
    [DbContext(typeof(propertyContext))]
    partial class propertyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("propertiesService.Entities.storeProperty", b =>
                {
                    b.Property<int>("propertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("propertyLocation")
                        .HasColumnType("TEXT");

                    b.Property<string>("propertyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("propertyOwner")
                        .HasColumnType("TEXT");

                    b.Property<string>("propertyPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("propertyId");

                    b.ToTable("storeProperties");
                });
#pragma warning restore 612, 618
        }
    }
}
